version: "3.8"

services:
  sensordash:
    container_name: sensordash
    image: sensordash:latest
    ports:
      - "5000:5000/tcp"
    environment:
      API_KEY_RO: '${MERAKI_HOME_NET_RO}'
    restart: unless-stopped