version: "3.8"

services:
  sensordash:
    container_name: sensordash
    image: sensordash:latest
    ports:
      - "5000:5000/tcp"
    environment:
      MERAKI_HOME_NET_RO: '${MERAKI_HOME_NET_RO}'
    restart: unless-stopped
    depends_on:
    - startup
    volumes:
      - '.:/app'
    command: pip3 install -r requirements.txt